- name: Configure Web Server
  hosts: all
  become: true

  tasks:

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create index page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <h1>Mantra Application</h1>
          <p>Deployed using Terraform + Ansible</p>
